<a href="https://colab.research.google.com/github/edwincshony/luminar_codes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

array is faster than list.

array = An array is a fundamental, linear data structure that stores a collection of elements of the same data type in contiguous memory locations.

In [51]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.4
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

In [52]:
import numpy as np

In [53]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [54]:
a.ndim

1

In [55]:
tp = type(a)

tp

numpy.ndarray

1dimensional ----> 1 2 3 4 5

2dimensional ----> 1 2 3

                   4 5 6

                   7 8 9
                   

In [56]:
b = np.array([1,2,3,4,3.5])
b

array([1. , 2. , 3. , 4. , 3.5])

int → promoted to float if any float is present

float → promoted to str if any string is present

In [57]:
c = np.array([3.5,"edwin"])
c

array(['3.5', 'edwin'], dtype='<U32')

In [58]:
c.size

2

In [59]:
#2d array
# dimensions: rows, and columns
ab = np.array(([1,2],[2,3],[3,4]))
ab

array([[1, 2],
       [2, 3],
       [3, 4]])

In [60]:
ab.shape

(3, 2)

In [61]:
ab.ndim

2

In [62]:
ab[1][1]

np.int64(3)

In [63]:
# create a 2D array with (3,3)
abc = np.array([[1,2,2],[2,1,1],[3,4,5]])
abc

array([[1, 2, 2],
       [2, 1, 1],
       [3, 4, 5]])

In [64]:
ab.ndim

2

In [65]:
abc.shape

(3, 3)

In [66]:
tp1 = type(abc)
tp1

numpy.ndarray

In [67]:
#3d array
# dimensions: layers (or depth), rows, and columns

bn=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

bn

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [68]:
bn.shape

(3, 2, 2)

In [69]:
bn.ndim

3

In [70]:
# (depth,row,column)
# create a 3d array with (3,3,3)
# create a 2d array with shape(2,4)
# create a 3d array with shape(2,3,3)
# create a 3d array with shape(3,2,2)

In [71]:
q4 = np.array([[[2,1],[2,2]],[[5,6],[7,8]],[[4,5],[5,8]]])
q4

array([[[2, 1],
        [2, 2]],

       [[5, 6],
        [7, 8]],

       [[4, 5],
        [5, 8]]])

In [72]:
q4.shape

(3, 2, 2)

In [73]:
q2 = np.array([[1,2,3,4],[5,6,7,8]])
q2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
q2.shape

(2, 4)

In [75]:
q3 = np.array([[[2,3,4],[4,5,6],[7,8,9]],[[4,5,6],[4,7,8],[8,9,7]]])
q3

array([[[2, 3, 4],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [4, 7, 8],
        [8, 9, 7]]])

In [76]:
q3.shape

(2, 3, 3)

In [77]:
q1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[5,4,7],[7,8,9],[5,6,8]],[[5,7,8],[8,8,8],[1,2,3]]])
q1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[5, 4, 7],
        [7, 8, 9],
        [5, 6, 8]],

       [[5, 7, 8],
        [8, 8, 8],
        [1, 2, 3]]])

In [78]:
q1.shape

(3, 3, 3)

In [79]:
# 07-04-2026 11:30 - 1:30 PM session

# forward indexing
# backward indexing

#numpy array are :
#faster
# memory efficient
# support mathematical operations directly

# list is a basic array

# images are stored as arrays

# | Feature          | Python List                          | NumPy Array                         |
# |------------------|--------------------------------------|-------------------------------------|
# | Speed            | Slower                               | Faster                              |
# | Data Type        | Can store mixed data types           | Usually same data type              |
# | Math Operations  | Cannot perform directly (needs loops)| Can perform directly (vectorized)   |
# | Used In          | General Python programming           | AI, ML, Data Science                |

# print(a[0]) #forward indexing
# print(a[-1]) # backward indexing

# array([1,2,3,4,5])
# [2 3] elements only

print(a[1:3])



[2 3]


In [80]:
x=np.array([1,2,3,4,5,6])
print(x)
print(x[1:3])
print(x[0])
print(x[-1])

[1 2 3 4 5 6]
[2 3]
1
6


In [81]:
h = np.array([[1,2],[2,3],[3,4],[5,6]])
h

array([[1, 2],
       [2, 3],
       [3, 4],
       [5, 6]])

In [82]:
#     0       1

#r1-0    1       2
#r2-1    2       3
#r3    3       4
#r4    5       6

In [83]:
print(h[0])

[1 2]


In [84]:
print(h[0,0])

1


In [85]:
print(h[2])

[3 4]


In [86]:
j = np.array([[1,2,5],[2,3,7],[3,4,8],[5,6,9]])
j
"""
🔷 Beginner Rule (memorize this)
Use single index (0) → flatten result
Use slice (0:1) → keep 2D structure

:      → all elements
0:     → from 0 to end
:2     → from start to index 1
"""

array([[1, 2, 5],
       [2, 3, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [100]:
print(j[2,1:]) #q1
print(j[3,0:2]) #q2
print(j[0,-1]) ##q3
print(j[3,0]) #q3 other answer
print(j[2,0:2],j[3,0:2]) #q4
print(j[2:4, 0:2]) #q4 other answer
"""
2:4 → selects rows 2 and 3
0:2 → selects columns 0 and 1
"""
print(j[0:,0])
print(j[0:,0:1])

[4 8]
[5 6]
5
5
[3 4] [5 6]
[[3 4]
 [5 6]]
[1 2 3 5]
[[1]
 [2]
 [3]
 [5]]


In [88]:
k = np.array([[1,2,3,4],[4,5,6,7],[9,8,10,11]])
k

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9,  8, 10, 11]])

In [89]:
# [4,5,6,7]

print(k[1])

[4 5 6 7]


In [90]:
# [[5,6],[8,10]]

print(k[1,1:-1],k[2,1:-1])
print(k[1:3,1:3])
"""
2:4 → selects rows 2 and 3
0:2 → selects columns 0 and 1
"""

[5 6] [ 8 10]
[[ 5  6]
 [ 8 10]]


In [102]:
# [[6,7],[10,11]]

print(k[1:3,2:4]) # stop defined allengilum scn ela last vare povum for :

[[ 6  7]
 [10 11]]


In [92]:
"""
array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9,  8, 10, 11]])
"""
##5
print(k[1,1])

#[10,11]
print(k[2,2:])
#[9,8]
print(k[2,0:2])
#

5
[10 11]
[9 8]


In [93]:
# arange
"""
np.arange() creates a sequence of numbers evenly spaced within a given range.
np.arange(start, stop, step)
"""
kl = np.arange(1,101,2)
kl

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [94]:
# print multiples of 3 upto 10
p = np.arange(3,11,3)
p


array([3, 6, 9])

In [95]:
#reshape
"""
reshape() changes the shape (dimensions) of an array without changing its data.
array.reshape(rows, columns)
Or more generally:
array.reshape(new_shape)
rows × columns = total elements, otherwise error
"""

jk = np.array([[1,2,3,4],[4,5,6,7],[9,8,6,5]])
jk

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 8, 6, 5]])

In [104]:
jk.reshape([6,2])

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7],
       [9, 8],
       [6, 5]])

In [97]:
jk.reshape([4,3])

array([[1, 2, 3],
       [4, 4, 5],
       [6, 7, 9],
       [8, 6, 5]])

In [106]:
# q1a)create one dimensional array multiple of 4 upto 40 (arange)
ar = np.arange(4,41,4)
ar #[ 4  8 12 16 20 24 28 32 36 40]

# q1b)convert it in possible 2 dimensional shapes

"""The array has 10 elements, so valid 2D shapes must multiply to 10:

(1 × 10)
(2 × 5)
(5 × 2)
(10 × 1)"""

# 1 x 10
print(ar.reshape(1, 10))

# 2 x 5
print(ar.reshape(2, 5))

# 5 x 2
print(ar.reshape(5, 2))

# 10 x 1
print(ar.reshape(10, 1))

[[ 4  8 12 16 20 24 28 32 36 40]]
[[ 4  8 12 16 20]
 [24 28 32 36 40]]
[[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]
[[ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]
 [28]
 [32]
 [36]
 [40]]
